# -*- coding: utf-8 -*-
"""Python_strings.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rbXwq51vrqg4qOVqnHhZNZmMH3qAoiEO

# 1. Print hello world
"""

print("Hello World!")

"""# 2. Write a code to reverse a string"""

def reverse_string(text):
  reversed = ""
  for char in text:
    reversed = char + reversed
  return reversed
print(reverse_string("Marshmallow"))


# or

def reverse_string(text):
  return text[::-1]
print(reverse_string("kitchen"))

"""# 3. Write a code to check if a string is a palindrome or not"""

def pal_num(text):
  cleaned = text.replace(" ","").lower() # clean the string
  return cleaned == cleaned[::-1]  #reverse and return
print(pal_num("MaDam"))

print(pal_num("Dinosaur"))

"""# 4. Count the number of words in a string"""

def count_words(s):
  word = s.split()
  return len(word)
#output1:
print(count_words("This is a sentence"))
# output2:
print(count_words("I love Bioinformtics"))

"""# 4. Write a program to count characters in a string"""

def count_characters(q):
  characters = q.replace(" ", "")
  return len(characters)

print(count_characters("Come here"))

"""# 5. Find number of vowels in String"""

def find_vowels(t):
  vowels = [char for char in t.lower() if char in "aeiou"]
  return len(vowels)

print(find_vowels(" I love learning"))